version: '3.2'

services:
  syslog:
    build: build
    volumes: 
      - "./syslog/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf"    
      - "./syslog/logrotate.d/odoo:/etc/logrotate.d/odoo"
      - "/srv/container-volumes/log:/var/log"
    ports:
      - "127.0.0.1:514:514/udp"
    restart: always
