version: '3.2'

# Odoo Container

#arn:aws:secretsmanager:eu-west-2:136182278273:secret:gpit-odoo-image-L9I2RP

# .env contains all the container specific details

services:
  odoo:
    &odoo
    image: ${ODOO_IMAGE}:${ODOO_IMAGE_VERSION}
    volumes:
    - "${CONTAINER_VOLUME}/invoicing/odoo/extra-addons:/mnt/extra-addons:rw"
    - "./odoo/etc/:/etc/odoo:rw"
    ports:
    - "8069:8069"
    - "8070:8072"
    environment:
      USER: "${ODOO_POSTGRES_USER}"
      PASSWORD: "${ODOO_POSTGRES_PASSWORD}"
    command: --max-cron-threads 0 --workers 8 --log-handler=:INFO
    restart: unless-stopped
    logging:
      driver: 'syslog'
      options:
        syslog-address: 'udp://127.0.0.1:514'
        tag: 'odoo'

  odoo-cron:
    << : *odoo
    ports: 
    - "8072"
    command: --max-cron-threads 8 --no-xmlrpc --database ${ODOO_CRON_DB}
    logging:
      driver: 'syslog'
      options:
        syslog-address: 'udp://127.0.0.1:514'
        tag: 'odoo-cron'
