#!/bin/bash


mkdir -p /srv/container-deployment/odoo/etc
mkdir -p /srv/container-volumes
cp /home/gpitsupport/deploy/odoo.conf /srv/container-deployment/odoo/etc
cp /home/gpitsupport/deploy/docker-compose.yml /srv/container-deployment/
cp /home/gpitsupport/deploy/.env /srv/container-deployment/
cp /home/gpitsupport/deploy/odoo_permissions.sh /srv/container-deployment/
sed -i -e 's|${rds_host}|'$1'|g' /srv/container-deployment/odoo/etc/odoo.conf
sed -i -e 's|${rds_pass}|'$2'|g' /srv/container-deployment/odoo/etc/odoo.conf
sed -i -e 's|${admin_pass}|'$3'|g' /srv/container-deployment/odoo/etc/odoo.conf
sed -i -e 's|${limit_time_cpu}|'$7'|g' /srv/container-deployment/odoo/etc/odoo.conf
sed -i -e 's|${limit_time_real}|'$8'|g' /srv/container-deployment/odoo/etc/odoo.conf
sed -i -e 's|${smtp_password}|'$9'|g' /srv/container-deployment/odoo/etc/odoo.conf
sed -i -e 's|${odoo_password}|'$2'|g' /srv/container-deployment/.env
sed -i -e 's|${postgres_password}|'$4'|g' /srv/container-deployment/.env
sed -i -e 's|${odoo_image_version}|'$5'|g' /srv/container-deployment/.env
sed -i -e 's|${odoo_image}|'$6'|g' /srv/container-deployment/.env
sed -i -e 's|${odoo_cron_db}|'${10}'|g' /srv/container-deployment/.env
systemctl restart docker
cd /srv/container-deployment
docker-compose down -v --rmi all --remove-orphans
docker-compose pull
docker-compose up -d && bash ./odoo_permissions.sh
docker-compose logs -f odoo > /srv/logs/odoo.log 2>&1 &
docker-compose logs -f odoo-cron > /srv/logs/odoo-cron.log 2>&1 &