#!/bin/bash
docker-compose down -v --rmi all --remove-orphans
docker-compose pull
docker-compose stop odoo && docker-compose run --rm odoo -d gpit-uat -u billing,op_import_data --stop-after-init && docker-compose up -d